import React from 'react';
import { Eye, Download } from 'lucide-react';
import { clsx } from 'clsx';

export default function ReportTable({ reports, onView, onDownload }) {
  return (
    <div className="bg-white rounded-2xl shadow-sm border border-neutral-100 overflow-hidden w-full">
      <div className="overflow-x-auto">
        <table className="w-full text-left min-w-[900px]">
          <thead>
            <tr className="bg-neutral-50 text-neutral-500 text-[10px] uppercase tracking-wider border-b border-neutral-100">
              <th className="p-4 font-semibold">Report Details</th>
              <th className="p-4 font-semibold">Generated By</th>
              <th className="p-4 font-semibold">Filters Applied</th>
              <th className="p-4 font-semibold">Format</th>
              <th className="p-4 font-semibold">Status</th>
              <th className="p-4 font-semibold text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="text-sm divide-y divide-neutral-100">
            {reports.map((rpt) => (
              <tr key={rpt.id} className="hover:bg-neutral-50 transition-colors">
                <td className="p-4">
                  <div className="font-bold text-neutral-900">{rpt.name}</div>
                  <div className="text-[10px] font-bold text-neutral-400 uppercase tracking-wider mt-0.5">{rpt.id} • {new Date(rpt.date).toLocaleString()}</div>
                </td>
                <td className="p-4 font-semibold text-neutral-700">{rpt.generatedBy}</td>
                <td className="p-4 text-xs font-semibold text-neutral-500">{rpt.filters}</td>
                <td className="p-4">
                  <span className="px-2 py-1 rounded bg-neutral-100 text-neutral-600 text-[10px] font-bold uppercase tracking-wider">
                    {rpt.format}
                  </span>
                </td>
                <td className="p-4">
                  <span className={clsx(
                    "px-2 py-1 rounded-lg text-[10px] font-bold uppercase tracking-wider",
                    rpt.status === 'Available' ? 'bg-green-100 text-green-700' : 'bg-neutral-100 text-neutral-700'
                  )}>
                    {rpt.status}
                  </span>
                </td>
                <td className="p-4 text-right">
                  <div className="flex justify-end gap-1.5">
                    {rpt.format === 'PDF' && (
                      <button onClick={() => onView(rpt)} title="View Preview" className="p-1.5 text-neutral-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors"><Eye className="w-4 h-4" /></button>
                    )}
                    <button onClick={() => onDownload(rpt)} title="Download" className="p-1.5 text-neutral-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors"><Download className="w-4 h-4" /></button>
                  </div>
                </td>
              </tr>
            ))}
            {reports.length === 0 && (
              <tr><td colSpan="6" className="p-8 text-center text-neutral-500 font-semibold text-sm">No reports generated yet.</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
